### ISSUE TITLE
Advanced Records Lag

### ISSUE THREAD

**Issue by ItsNiklas** [Beezig/Beezig#8]
On some situations, the game still freezes when using Advanced Records due to not using a new thread on every HiveAPI method.
Please create a new thread in the missing ones or create a new thread on every occasion HiveAPI is called :)

**Comment by roccodev** [comment]
This won't be implemented. I've tried with the threads but, it's needed to join the main thread, otherwise the message will be sent after the data is fetched, therefore showing the normal records and the advanced records separately.

Joining the threads waits for the other thread to finish, causing lag.

**Comment by roccodev** [comment]
That is fixed in the new artest branch!
